### PR TITLE
misc cleanup and add buildkite

### PR DESCRIPTION
**Pull request by CarloLucibello**

### CODE REVIEW

**Comment by yuehhua** [comment]
Thank you so much for CUDA CI.

**Comment by CarloLucibello** [comment]
Hoping @DhairyaLGandhi or @maleadt will be kind enough to authorize buildkite for this repo

**Comment by yuehhua** [comment]
I have been thinking about adding buildkite for this repo. When I checked docs, I found that an authorization is required, and don't know who to contact with.

**Comment by DhairyaLGandhi** [comment]
@yuehhua  I've added a BK pipeline for this repo. You can add a web hook to start running builds with CUDA, or let me know and I can help set it up for you.

**Pull request merged**
